language: python

python:
  - 3.4

env:
  - NFSN_DEST=/home/public
    NFSN_HOST=ssh.phx.nearlyfreespeech.net

addons:
  ssh_known_hosts: ssh.phx.nearlyfreespeech.net

before_install:
  - '[ "$TRAVIS_BRANCH" == "master" ] || export NFSN_DEST="$NFSN_DEST/$TRAVIS_BRANCH"'
  - touch .ssh_key && chmod 600 .ssh_key
  - openssl aes-256-cbc -K $encrypted_fd059ec139f0_key -iv $encrypted_fd059ec139f0_iv -in nfsn.enc -out .ssh_key -d
  - eval $(ssh-agent -s)
  - ssh-add .ssh_key

install:
  - pip install -r requirements.txt

script:
  - cd docs
  - sphinx-build . _build/html
  - sed -i '\@https\?://@! s@\(href\|src\|action\)="\(\w\)@\1="/\2@g' _build/html/404.html

after_success:
  - cd _build/html
  - rsync -icrz --delete --delete-excluded --exclude={.doctrees,.buildinfo} ./ $NFSN_LOGIN@$NFSN_HOST:$NFSN_DEST
