# Configure.
addons:
  ssh_known_hosts: ssh.phx.nearlyfreespeech.net
env:
  - NFSN_DEST=/home/public
    NFSN_HOST=ssh.phx.nearlyfreespeech.net
language: python
python: 3.5
sudo: false

# Run.
before_install:
  - '[ "$TRAVIS_BRANCH" == "master" ] || export NFSN_DEST="$NFSN_DEST/$TRAVIS_BRANCH"'
install: make bootstrap
script:
  - make build
  - sed -i '\@https\?://@! s@\(href\|src\|action\)="\(\w\)@\1="/\2@g' docs/_build/html/404.html
after_success:
  - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
  - openssl aes-256-cbc -d -K "$encrypted_fd059ec139f0_key" -iv "$encrypted_fd059ec139f0_iv" < docs/key.enc > docs/key
    && ssh-add docs/key
  - cd docs/_build/html
  - rsync -icrz --delete --delete-excluded --exclude={.doctrees,.buildinfo} ./ $NFSN_LOGIN@$NFSN_HOST:$NFSN_DEST
