# Configure.
addons:
  ssh_known_hosts: ssh.phx.nearlyfreespeech.net
language: python
python: 3.5
sudo: false

# Run.
install: pip install -r requirements.txt
script: sphinx-build -W docs docs/_build/html
after_success:
  - eval "$(ssh-agent -s)"; touch key; chmod 0600 key
  - openssl aes-256-cbc -d -K $encrypted_fd059ec139f0_key -iv $encrypted_fd059ec139f0_iv < key.enc > key && ssh-add key
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git remote add nfsn "robpol86_robpol86@ssh.phx.nearlyfreespeech.net:/home/private/repo"
  - export ${!TRAVIS*}
  - sphinx-versioning push -P nfsn docs nfsn-pages .
