gems:
    - jekyll-redirect-from
    - jekyll-sitemap
highlighter:    pygments
lsi:            false
permalink:      /:categories/:title
timezone:       America/Los_Angeles
url:            http://robpol86.com
