gems:
    - jekyll-sitemap
highlighter:    pygments
lsi:            false
permalink:      /:categories/:title
safe:           true
timezone:       America/Los_Angeles
url:            http://robpol86.com
